// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgONN56Baaqp34bxChmEZ18wCCh3E5bqQ',
    appId: '1:871458519395:web:f201d2eec5f7f55afd7b56',
    messagingSenderId: '871458519395',
    projectId: 'learny-78497',
    authDomain: 'learny-78497.firebaseapp.com',
    storageBucket: 'learny-78497.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1TGZpHK-kb7ciAfyT62P5xx6blfHHYlQ',
    appId: '1:871458519395:android:1fdc44e4fbef2430fd7b56',
    messagingSenderId: '871458519395',
    projectId: 'learny-78497',
    storageBucket: 'learny-78497.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhfXDzQtsmuGvQLsxchQp2dq9bqbyUbrE',
    appId: '1:871458519395:ios:380a08f31b648211fd7b56',
    messagingSenderId: '871458519395',
    projectId: 'learny-78497',
    storageBucket: 'learny-78497.appspot.com',
    iosBundleId: 'com.example.leanify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhfXDzQtsmuGvQLsxchQp2dq9bqbyUbrE',
    appId: '1:871458519395:ios:1c63f4765a9a6d38fd7b56',
    messagingSenderId: '871458519395',
    projectId: 'learny-78497',
    storageBucket: 'learny-78497.appspot.com',
    iosBundleId: 'com.example.leanify.RunnerTests',
  );
}
